Add configuration for golang-migrate/migrate
cashapp/hermit-packages pull request #144
Opened 2022-04-29 17:42 UTC by zikani03

Add entry for golang-migrate/migrate.

2022-05-11 00:10 UTC, alecthomas commented
Sorry this took so long!

2022-05-11 00:19 UTC, alecthomas requested changes

2022-05-11 00:19 UTC, alecthomas commented on migrate.hcl
> +version "v4.15.2" {
The version number can't include `v`. You'll have to insert the v below into the URLs.

2022-05-11 21:45 UTC, zikani03 commented
No problem @alecthomas,  I have pushed the fix.

2022-05-12 01:19 UTC, alecthomas commented
I think you also need to rebase to current master.

2022-05-12 01:46 UTC, zikani03 commented
@alecthomas done. Thought of rebasing when I realized the github-actions automatically upgrade (very cool btw), don't know how it slipped my mind.

2022-05-12 09:44 UTC, merged

2022-05-12 09:44 UTC, alecthomas commented
Thanks!