feat: add sonar-scanner-cli
cashapp/hermit-packages pull request #536
Opened 2024-11-17 04:13 UTC by nickajacks1

Validated with an enterprise SonarQube instance in CI.

2024-11-17 04:23 UTC, nickajacks1 commented
The CI check failed because this version of sonar-scanner-cli was built by a too new version of Java.  `hermit test -t sonar-scanner-cli-6.2.1.4610` executes successfully for me on Ubuntu 24.10 and Ubuntu 24.04.

2024-11-17 23:09 UTC, alecthomas requested changes

2024-11-17 23:09 UTC, alecthomas commented on sonar-scanner-cli.hcl
> +source = "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610.zip"
```suggestion
source = "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${version}.zip"
```

2024-11-17 23:09 UTC, alecthomas commented
> The CI check failed because this version of sonar-scanner-cli was built by a too new version of Java. `hermit test -t sonar-scanner-cli-6.2.1.4610` executes successfully for me on Ubuntu 24.10 and Ubuntu 24.04.

Makes sense.

2024-11-17 23:14 UTC, nickajacks1 commented on sonar-scanner-cli.hcl
> +source = "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610.zip"
Oops, thanks.

2024-11-18 02:00 UTC, alecthomas approved these changes

2024-11-18 02:00 UTC, merged